language: node_js

node_js:
  - '14'
  - '12'
  - '10'

os:
  - linux
  - osx
  - windows

env:
  global:
    - FORCE_COLOR=1

install:
  - npm install

script:
  - npm test

jobs:
  exclude:
    # https://github.com/Automattic/node-canvas/issues/1626
    - os: osx
      node_js: '14'
  include:
    - stage: npm release
      if: tag IS present
      os: linux
      node_js: '14'
      install: skip
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: LGsZieQqkr5K+MtFxR0Ml3UootpZrcGWJrkHMJ5CNcELDIFVuberuHjQ3yNdeIfmeE6aGHJlBMYx3DVC5LxF8xoPn/Jjag2BI9xD5InFJKMyavIhDTXIyrFvAR+WoWSOOSPi6O6kSHduMO5em0aDio5hLPdMp2igefeqMcHtJFIttTNPTOTnycImphkf2M+31PrMzX+b9SDBc5brgS8xCMzl9zzACk3KytVTXHOQbAnUqmdf7QpT0LwSYi/9WZ3m/18kqkeE1zylGrIWyKb95UvOzMfeW5vvzWM5fAV2ZfaqbVs1fwsA3cm0ez/H0crKn/46txWWkraDPumrdAZXgmQ2hKVnRNIEYHW0ewJF+NEFOKFjAx3TbfaEsbrMwaBgkvkq94H9Peq000RdYIJk+JPSs1fWjisf/wEu774ZxqEAMasTW+uOscCwDbO4Q99U75LfmgoaHsvpTGQFrc3oOGS0YnbQgojVCuAuWm7GN3hhG4qeOcSfAXU3aT+zr9C0jbA5hd6YCY1AkOJTqVj5ML3DUok3u0RH98Dh/BgvBZK/fcezRpRfkBcmvGcu5bGAX6yJ2El5HQAU1C0apDOOdqXho0wipzXogtUM7CEBoc6AO7SjcwwdgV6aawlRYu5FIDzoUDW6wB3DLl3/w6dclkGSFuojVZHeW6r639DDL2s=
        on:
          tags: true
          repo: catdad/svg-app-icon
